name: ddr-v${oc.env:DDR_VERSION,dev}-plots
mode: routing
geodataset: lynker_hydrofabric
np_seed: 1
seed: 0
device: 0
s3_region: us-east-2

data_sources:
  geospatial_fabric_gpkg: ./../../data/conus_nextgen.gpkg
  conus_adjacency: ./../../data/hydrofabric_v2.2_conus_adjacency.zarr
  statistics: ./../../data/

params:
  save_path: ./model

experiment:
  checkpoint: ./ddr_v0.1.0a2_trained_model_weights.pt

kan:
  hidden_size: 11
  input_var_names:
    - glaciers
    - aridity
    - meanelevation
    - meanP
    - log_uparea
  num_hidden_layers: 1
  learnable_parameters:
  - n
  - q_spatial
  grid: 3
  k: 3

# To enable leakance (groundwater-surface water exchange):
# params:
#   use_leakance: true
# kan:
#   learnable_parameters: [n, q_spatial, K_D, d_gw]
#   off_parameters: [K_D, d_gw]
